spring:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  application:
    name: SpringJWT17
  datasource:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
    username: poly
    url:
jwt:
  token:
    creator: poly
    access:
      valid:
        time: 300
      name: jwtAcccessToken
    refresh:
      valid:
        time: 3000
      name: jwtRefreshToken
  secret:
    key:
server:
  port: '15000'